# Site settings
title: Mrudul's Running Blog.
email: mrudulpen (at) gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This blog captures all Tips and Tricks used to get about my job done.
baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://yourdomain.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  mrudulp

# Build settings
markdown: kramdown
